version: '3'

services:
    postgres_db: 
        build: ./postgres-docker
        environment:
            - POSTGRES_PASSWORD=docker
        ports:
            - 5432:5432
            
    shiny_server:
        build: ./shiny-docker
        volumes:
            - ./spotify_connect_shiny:/srv/shiny-server/spotify_app
            - ./logs:/var/log/shiny-server/
        ports:
            - 80:3838
        environment:
            - USER=shiny
