FROM postgres:11.3

# COPY my_init.sh /docker-entrypoint-initdb.d/

# Build: docker build --tag=is6481-postgres .
# To run: docker run --rm   --name lab1-postgres -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -e DB_HOST=127.0.0.1 is6481-lab1-postgres
# Open RStudio - In browser go to "localhost:8787"

# Shell in container: docker exec -it lab1-postgres bash
